title: Juan León | Engineering
description: Portafolio de Ingeniería Mecatrónica, Wearables y Diseño de Hardware.
author: Juan León

# GitHub Pages: modo recomendado
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# --- CONFIGURACIÓN DE URL (¡OJO AQUÍ!) ---
# Asegúrate de que esto coincida con tu usuario real
url: "https://JuanLeon05.github.io"
baseurl: "/portafolio-JL"

# --- ESTILO VISUAL (Vibe Royal Blood/NBT) ---
color_scheme: dark  # Forzamos el modo oscuro por defecto (Dark Mode)

# Configuración Formato
just_the_docs:
  custom_css:
    - "assets/css/custom.css" # Aquí pondremos tus toques personales luego
  footer_content: "Diseñado con energía ⚡ y código."

# Búsqueda
search_enabled: true
search:
  heading_level: 2
  placeholder: "Buscar proyectos..."

# Botones de arriba a la derecha
aux_links:
  "Ver en GitHub":
    - "https://github.com/JuanLeon05/portafolio-JL"
  "LinkedIn":
    - "https://linkedin.com/in/TU_USUARIO" # ¡Pon tu LinkedIn real si tienes!

# Enlaces limpios
permalink: pretty

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor"